import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useCallback, useEffect, useMemo, useState } from "react";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [id, setId] = useState("");
  const [pw, setPw] = useState("");
  const [err, setErr] = useState("");

  const onChangeId = useMemo(() => {
    return (e: React.ChangeEvent<HTMLInputElement>) => {
      setId(e.target.value);
    };
  }, [id]);

  const onChangePw = useMemo(() => {
    return (e: React.ChangeEvent<HTMLInputElement>) => {
      setPw(e.target.value);
      console.log("pw: ", pw);
    };
  }, [pw]);

  const onLogin = async () => {
    console.log("login");
    const body = {
      username: id,
      password: pw,
    };
    try {
      const res = await axios.post("/auth/login", body, {
        withCredentials: true,
      });
      console.log(res);
    } catch (error: any) {
      console.warn(error);
      setErr(error);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center w-screen h-screen bg-gray-50">
        <div className="h-10 w-80 grid justify-center text-3xl font-bold text-red-200 underline bg-wb mb-10">
          ! Hello World !
        </div>
        <input
          type={"text"}
          className="grid justify-center w-r1/3 min-w-128 h-16 bg-blue-200 rounded-3xl mb-10 px-10 dark:focus:bg-blue-300"
          id="id"
          onChange={(e) => onChangeId(e)}
        />
        <input
          type={"password"}
          className="grid justify-center w-r1/3 min-w-128 h-16 bg-blue-200 rounded-3xl mb-10 px-10 dark:focus:bg-blue-300"
          id="pw"
          onChange={(e) => onChangePw(e)}
        />
        <div className="grid">
          <button
            className="flex justify-center items-center w-300px h-60px bg-blue-200 text-2xl"
            onClick={onLogin}
          >
            로그인
          </button>
          <div className="flex mt-10 2-"></div>
        </div>
      </main>
    </>
  );
}
