import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid items-center justify-center w-r1/2 h-128 bg-red-100">
        <div className="text-3xl font-bold text-red-200 underline bg-black">
          Hello World
        </div>
        <div className="w-80 h-80 bg-blue-200" />
      </main>
    </>
  );
}
